name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip build-essential libstdc++6 aidl
          sudo apt install -y python3 python3-pip ipython3 autoconf
          sudo apt install -y build-essential libltdl-dev libffi-dev libssl-dev python3-dev zip
          
          # Install Cython using pip
          python3 -m pip install --upgrade pip
          python3 -m pip install cython==0.29.21
          
          # Install Buildozer
          git clone https://github.com/kivy/buildozer.git
          cd buildozer
          sudo python3 setup.py install
          
          # Install python-for-android
          python3 -m pip install python-for-android

      - name: Check for Installed Dependencies
        run: |
          python3 -m pip show cython
          python3 -m pip show python-for-android
          which buildozer

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Android SDK
        run: |
          echo "sdk.dir=$HOME/android-sdk" > local.properties
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          
          # Unzip the command-line tools directly into the latest directory
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
          
          # Move the extracted cmdline-tools folder up one level to the latest directory
          mv $HOME/android-sdk/cmdline-tools/latest/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          
          # Clean up the now empty cmdline-tools directory
          rmdir $HOME/android-sdk/cmdline-tools/latest/cmdline-tools
          
          # Install Android SDK tools and Build-Tools (using version 30.0.3 for stability)
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3" \
          "extras;android;m2repository" \
          "tools"
          
          # Check if the required build tools are installed
          if [ ! -d "$HOME/android-sdk/build-tools/30.0.3" ]; then
            echo "Build-tools not found, installation may have failed."
            exit 1
          fi

      - name: Add Buildozer and Android SDK to PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Copy aidl binary to Build Tools
        run: |
          cp /usr/bin/aidl $HOME/android-sdk/build-tools/30.0.3/
          chmod -R 777 $HOME/android-sdk/build-tools/30.0.3/

      - name: Build APK
        run: |
          mkdir -p logs
          buildozer -v android debug --log_level 2 > logs/buildozer_log.txt

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk

      - name: Store Buildozer Logs
        uses: actions/upload-artifact@v4
        with:
          name: buildozer_logs
          path: logs/buildozer_log.txt
