name: Build APK - Facial Recognition System

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip build-essential libstdc++6 \
                                  autoconf automake libtool pkg-config cmake \
                                  libffi-dev libssl-dev
          python -m pip install --upgrade pip wheel
          pip install --upgrade Cython==0.29.21
          pip install buildozer==1.5.0
          pip install --no-cache-dir kivy==2.3.0

      - name: Set up Android SDK and NDK
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;30.0.3" \
            "platforms;android-31" \
            "ndk;25.2.9519653"
      
      - name: Set Environment Variables
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Configure buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = Facial Recognition System
          package.name = facialrecognition
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy==2.3.0,pillow,numpy,opencv-python-headless
          orientation = portrait
          osx.python_version = 3
          osx.kivy_version = 2.3.0
          fullscreen = 0
          android.archs = arm64-v8a, armeabi-v7a
          android.permissions = INTERNET,CAMERA,WRITE_EXTERNAL_STORAGE
          android.api = 31
          android.minapi = 21
          android.ndk_path = $ANDROID_NDK_HOME
          android.sdk_path = $ANDROID_HOME
          android.gradle_dependencies = org.tensorflow:tensorflow-lite-support:0.3.0,org.tensorflow:tensorflow-lite-metadata:0.3.0
          p4a.branch = master
          p4a.bootstrap = sdl2
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Create main.py
        run: |
          cat > main.py << EOF
          from kivy.app import App
          from kivy.uix.button import Button

          class FacialRecognitionApp(App):
              def build(self):
                  return Button(text='Hello World')

          if __name__ == '__main__':
              FacialRecognitionApp().run()
          EOF

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: facial_recognition_apk
          path: bin/*.apk

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: .buildozer/logs/buildozer.log
