name: Build Kivy APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-11-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
            libgl1 libgles2 mecab-ipadic-utf8

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade Cython==0.29.33 virtualenv
          pip install --upgrade buildozer==1.5.0
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses
        
      - name: Install Android SDK components
        run: |
          sdkmanager "platforms;android-31" "build-tools;30.0.3" "ndk;25.2.9519653"
          
      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = Facial Recognition App
          package.name = facialrecognitionapp
          package.domain = org.example
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,ttf
          version = 0.1
          requirements = python3,\
              kivy==2.2.1,\
              pillow,\
              numpy,\
              opencv-python,\
              plyer,\
              android
          
          orientation = portrait
          osx.python_version = 3
          osx.kivy_version = 2.2.1
          fullscreen = 0
          android.archs = arm64-v8a, armeabi-v7a
          android.allow_backup = True
          android.api = 31
          android.minapi = 21
          android.ndk = 25.2.9519653
          android.sdk = 31
          android.accept_sdk_license = True
          android.gradle_dependencies = org.tensorflow:tensorflow-lite-support:0.3.0,org.tensorflow:tensorflow-lite-metadata:0.3.0
          android.permissions = INTERNET,CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
          
          p4a.branch = develop
          p4a.bootstrap = sdl2
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF
          
      - name: Build APK
        run: |
          export PATH=$PATH:$ANDROID_HOME/tools/bin
          buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: facial_recognition_apk
          path: bin/*.apk
          
      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: .buildozer/logs/buildozer.log
