name: Build Kivy App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Buildozer
        run: pip install buildozer
      - name: Build Android APK
        run: buildozer android debug
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: *.apk
