name: Build Kivy APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            git \
            python3-pip \
            python3-setuptools \
            libssl-dev \
            libffi-dev \
            automake \
            autoconf \
            libtool \
            libltdl-dev \
            zip \
            unzip \
            openjdk-11-jdk

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython==0.29.36
          pip install --upgrade buildozer
          pip install -r requirements.txt

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk
          echo "y" | sudo apt-get install sdkmanager
          echo "y" | sdkmanager --sdk_root=$HOME/Android/Sdk "platforms;android-31" "build-tools;31.0.0" "ndk;25.2.9519653"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Update buildozer.spec
        run: |
          echo "Updating buildozer.spec..."
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^android.sdk_path =.*/android.sdk_path = $HOME\/Android\/Sdk/' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = $HOME\/Android\/Sdk\/ndk\/25.2.9519653/' buildozer.spec
          cat buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 1
          PATH: "$PATH:$HOME/.local/bin"
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          ANDROID_HOME: $HOME/Android/Sdk
          ANDROID_NDK_HOME: $HOME/Android/Sdk/ndk/25.2.9519653

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: bin/*.apk
