on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk

      - name: Running Gautam's Blog post workflow 
        uses: gautamkrishnar/blog-post-workflow@master
        id: blogpost_workflow
        with:
          comment_tag_name: ${{inputs.comment_tag_name}}
          commit_message: "Updated Badge with latest number of articles"
          feed_list: ${{inputs.feed_list}}
          max_post_count: 1000000
          output_only: true

      - name: Echo the length
        run: echo $(jq '. | length' /tmp/blog_post_workflow_output.json)
