name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository (updated to latest version)
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment (updated to latest version)
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-setuptools python3-dev python3-pip build-essential git
        sudo apt install -y libssl-dev libffi-dev python3-venv
        python3 -m pip install --upgrade pip

    # Step 4: Install Buildozer
    - name: Install Buildozer
      run: |
        python3 -m pip install --user buildozer
        export PATH=$HOME/.local/bin:$PATH

    # Step 5: Build Android APK with Buildozer
    - name: Build APK
      run: |
        buildozer init
        buildozer android debug

    # Step 6: Upload APK as a build artifact using the latest version
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk
