name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=myenv
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=myenv
    
    - name: Create test directory and sample test (if tests don't exist)
      run: |
        mkdir -p tests
        echo "def test_example(): assert 1 + 1 == 2" > tests/test_sample.py
    
    - name: Test with pytest
      run: |
        pytest tests/
    
    - name: Build APK
      uses: digreatbrian/buildozer-action@v2
      with:
        buildozer-cmd: buildozer -v android debug
        work-dir: .  # directory where your main.py file rests

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ./bin/*.apk
