name: Build APK - Facial Recognition System

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libstdc++6 \
                                  autoconf automake libtool pkg-config cmake \
                                  libffi-dev libssl-dev
          python -m pip install --upgrade pip wheel
          pip install --upgrade Cython==0.29.21
          pip install buildozer==1.5.0
          pip install --no-cache-dir kivy==2.3.0

      - name: Download Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools

      - name: Setup Android SDK
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;30.0.3" \
            "ndk;25.2.9519653"
      
      - name: Set Environment Variables
        run: |
          echo "ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Configure buildozer.spec
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = Facial Recognition System
          package.name = facialrecognition
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy==2.3.0,pillow,numpy
          orientation = portrait
          osx.python_version = 3
          osx.kivy_version = 2.3.0
          fullscreen = 0
          android.archs = arm64-v8a, armeabi-v7a
          android.permissions = INTERNET,CAMERA,WRITE_EXTERNAL_STORAGE
          android.api = 31
          android.minapi = 21
          android.ndk_path = $GITHUB_WORKSPACE/android-sdk/ndk/25.2.9519653
          android.sdk_path = $GITHUB_WORKSPACE/android-sdk
          android.accept_sdk_license = True
          android.gradle_dependencies = org.tensorflow:tensorflow-lite-support:0.3.0,org.tensorflow:tensorflow-lite-metadata:0.3.0
          p4a.branch = master
          p4a.bootstrap = sdl2
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Create main.py
        run: |
          cat > main.py << EOF
          from kivy.app import App
          from kivy.uix.button import Button

          class FacialRecognitionApp(App):
              def build(self):
                  return Button(text='Hello World')

          if __name__ == '__main__':
              FacialRecognitionApp().run()
          EOF

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: facial_recognition_apk
          path: bin/*.apk

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build_logs
          path: .buildozer/logs/buildozer.log
