name: Build APK and Update README with Blog Posts

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *' # Scheduled every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rests

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk

  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt install -y jq

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Updated README with the latest blog posts"
          feed_list: "https://esteetey.dev/rss.xml"
          max_post_count: 1000
          output_only: true

      - name: Saves count as an output
        id: count-step
        run: echo "::set-output name=articles_length::$(jq '. | length' /tmp/blog_post_workflow_output.json)"

      - name: Prints count
        run: echo ${{ steps.count-step.outputs.articles_length }}
