# This workflow will install Python dependencies, run tests, build APK, and upload APK artifact
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python & Build APK Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check pytest version
      run: |
        pytest --version

    - name: Test with pytest
      run: |
        pytest -q --maxfail=5 --disable-warnings

    - name: Generate test report
      run: |
        pytest --junitxml=results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.xml

    - name: Install dependencies for Buildozer
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev python3-pip libssl-dev libffi-dev
        sudo apt install -y libsqlite3-dev libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev
        pip install --upgrade Cython==0.29.28 virtualenv buildozer

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
      working-directory: . # Directory where your main.py and buildozer.spec files are located

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-package
        path: ./bin/*.apk
