name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # You can set your Python version here

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev \
              build-essential python3-dev python3-venv \
              cython autoconf automake libtool pkg-config zlib1g-dev \
              libsqlite3-dev curl unzip openjdk-8-jdk
          python -m pip install --upgrade pip
          pip install buildozer
          pip install Cython==0.29.19
          pip install python-for-android

      - name: Create directories
        run: |
          mkdir -p ~/.buildozer/android/platform
          sudo chmod 777 ~/.buildozer/android/platform

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug
        env:
          ANDROID_NDK_HOME: ${{ secrets.ANDROID_NDK_HOME }}
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FRS APK
          path: bin/*.apk
