name: Build Android App

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git
          pip3 install buildozer

      - name: Install Android dependencies
        run: |
          sudo apt install -y unzip
          buildozer android update

      - name: Build the Android package
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp.apk
          path: bin/*.apk  # Adjust if necessary to your APK output path
